// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package response

import (
	"errors"
	"fmt"
)

const (
	// StatusOK is a Status of type OK.
	StatusOK Status = iota
	// StatusNotFound is a Status of type NotFound.
	StatusNotFound
	// StatusInvalidURLParameter is a Status of type InvalidURLParameter.
	StatusInvalidURLParameter
	// StatusInvalidRequest is a Status of type InvalidRequest.
	StatusInvalidRequest
	// StatusUsedEmail is a Status of type UsedEmail.
	StatusUsedEmail
	// StatusIncorrectPassword is a Status of type IncorrectPassword.
	StatusIncorrectPassword
	// StatusSamePassword is a Status of type SamePassword.
	StatusSamePassword
	// StatusInvalidToken is a Status of type InvalidToken.
	StatusInvalidToken
	// StatusMissingToken is a Status of type MissingToken.
	StatusMissingToken
	// StatusMissingFile is a Status of type MissingFile.
	StatusMissingFile
	// StatusUnsupportedMediaType is a Status of type UnsupportedMediaType.
	StatusUnsupportedMediaType
	// StatusInternalServerError is a Status of type InternalServerError.
	StatusInternalServerError
)

var ErrInvalidStatus = errors.New("not a valid Status")

const _StatusName = "OKNotFoundInvalidURLParameterInvalidRequestUsedEmailIncorrectPasswordSamePasswordInvalidTokenMissingTokenMissingFileUnsupportedMediaTypeInternalServerError"

var _StatusMap = map[Status]string{
	StatusOK:                   _StatusName[0:2],
	StatusNotFound:             _StatusName[2:10],
	StatusInvalidURLParameter:  _StatusName[10:29],
	StatusInvalidRequest:       _StatusName[29:43],
	StatusUsedEmail:            _StatusName[43:52],
	StatusIncorrectPassword:    _StatusName[52:69],
	StatusSamePassword:         _StatusName[69:81],
	StatusInvalidToken:         _StatusName[81:93],
	StatusMissingToken:         _StatusName[93:105],
	StatusMissingFile:          _StatusName[105:116],
	StatusUnsupportedMediaType: _StatusName[116:136],
	StatusInternalServerError:  _StatusName[136:155],
}

// String implements the Stringer interface.
func (x Status) String() string {
	if str, ok := _StatusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Status(%d)", x)
}

var _StatusValue = map[string]Status{
	_StatusName[0:2]:     StatusOK,
	_StatusName[2:10]:    StatusNotFound,
	_StatusName[10:29]:   StatusInvalidURLParameter,
	_StatusName[29:43]:   StatusInvalidRequest,
	_StatusName[43:52]:   StatusUsedEmail,
	_StatusName[52:69]:   StatusIncorrectPassword,
	_StatusName[69:81]:   StatusSamePassword,
	_StatusName[81:93]:   StatusInvalidToken,
	_StatusName[93:105]:  StatusMissingToken,
	_StatusName[105:116]: StatusMissingFile,
	_StatusName[116:136]: StatusUnsupportedMediaType,
	_StatusName[136:155]: StatusInternalServerError,
}

// ParseStatus attempts to convert a string to a Status.
func ParseStatus(name string) (Status, error) {
	if x, ok := _StatusValue[name]; ok {
		return x, nil
	}
	return Status(0), fmt.Errorf("%s is %w", name, ErrInvalidStatus)
}

// MarshalText implements the text marshaller method.
func (x Status) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Status) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseStatus(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
