// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Films", testFilms)
	t.Run("FilmsAudits", testFilmsAudits)
	t.Run("Serieses", testSerieses)
	t.Run("SeriesesAudits", testSeriesesAudits)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("Films", testFilmsDelete)
	t.Run("FilmsAudits", testFilmsAuditsDelete)
	t.Run("Serieses", testSeriesesDelete)
	t.Run("SeriesesAudits", testSeriesesAuditsDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Films", testFilmsQueryDeleteAll)
	t.Run("FilmsAudits", testFilmsAuditsQueryDeleteAll)
	t.Run("Serieses", testSeriesesQueryDeleteAll)
	t.Run("SeriesesAudits", testSeriesesAuditsQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Films", testFilmsSliceDeleteAll)
	t.Run("FilmsAudits", testFilmsAuditsSliceDeleteAll)
	t.Run("Serieses", testSeriesesSliceDeleteAll)
	t.Run("SeriesesAudits", testSeriesesAuditsSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Films", testFilmsExists)
	t.Run("FilmsAudits", testFilmsAuditsExists)
	t.Run("Serieses", testSeriesesExists)
	t.Run("SeriesesAudits", testSeriesesAuditsExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("Films", testFilmsFind)
	t.Run("FilmsAudits", testFilmsAuditsFind)
	t.Run("Serieses", testSeriesesFind)
	t.Run("SeriesesAudits", testSeriesesAuditsFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("Films", testFilmsBind)
	t.Run("FilmsAudits", testFilmsAuditsBind)
	t.Run("Serieses", testSeriesesBind)
	t.Run("SeriesesAudits", testSeriesesAuditsBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("Films", testFilmsOne)
	t.Run("FilmsAudits", testFilmsAuditsOne)
	t.Run("Serieses", testSeriesesOne)
	t.Run("SeriesesAudits", testSeriesesAuditsOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("Films", testFilmsAll)
	t.Run("FilmsAudits", testFilmsAuditsAll)
	t.Run("Serieses", testSeriesesAll)
	t.Run("SeriesesAudits", testSeriesesAuditsAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("Films", testFilmsCount)
	t.Run("FilmsAudits", testFilmsAuditsCount)
	t.Run("Serieses", testSeriesesCount)
	t.Run("SeriesesAudits", testSeriesesAuditsCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("Films", testFilmsHooks)
	t.Run("FilmsAudits", testFilmsAuditsHooks)
	t.Run("Serieses", testSeriesesHooks)
	t.Run("SeriesesAudits", testSeriesesAuditsHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Films", testFilmsInsert)
	t.Run("Films", testFilmsInsertWhitelist)
	t.Run("FilmsAudits", testFilmsAuditsInsert)
	t.Run("FilmsAudits", testFilmsAuditsInsertWhitelist)
	t.Run("Serieses", testSeriesesInsert)
	t.Run("Serieses", testSeriesesInsertWhitelist)
	t.Run("SeriesesAudits", testSeriesesAuditsInsert)
	t.Run("SeriesesAudits", testSeriesesAuditsInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("FilmToUserUsingContributingUser", testFilmToOneUserUsingContributingUser)
	t.Run("FilmToSeriesUsingSeries", testFilmToOneSeriesUsingSeries)
	t.Run("SeriesToUserUsingContributingUser", testSeriesToOneUserUsingContributingUser)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("SeriesToSeriesFilms", testSeriesToManySeriesFilms)
	t.Run("UserToContributedFilms", testUserToManyContributedFilms)
	t.Run("UserToContributedSerieses", testUserToManyContributedSerieses)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("FilmToUserUsingContributedFilms", testFilmToOneSetOpUserUsingContributingUser)
	t.Run("FilmToSeriesUsingSeriesFilms", testFilmToOneSetOpSeriesUsingSeries)
	t.Run("SeriesToUserUsingContributedSerieses", testSeriesToOneSetOpUserUsingContributingUser)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("FilmToSeriesUsingSeriesFilms", testFilmToOneRemoveOpSeriesUsingSeries)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("SeriesToSeriesFilms", testSeriesToManyAddOpSeriesFilms)
	t.Run("UserToContributedFilms", testUserToManyAddOpContributedFilms)
	t.Run("UserToContributedSerieses", testUserToManyAddOpContributedSerieses)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("SeriesToSeriesFilms", testSeriesToManySetOpSeriesFilms)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("SeriesToSeriesFilms", testSeriesToManyRemoveOpSeriesFilms)
}

func TestReload(t *testing.T) {
	t.Run("Films", testFilmsReload)
	t.Run("FilmsAudits", testFilmsAuditsReload)
	t.Run("Serieses", testSeriesesReload)
	t.Run("SeriesesAudits", testSeriesesAuditsReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Films", testFilmsReloadAll)
	t.Run("FilmsAudits", testFilmsAuditsReloadAll)
	t.Run("Serieses", testSeriesesReloadAll)
	t.Run("SeriesesAudits", testSeriesesAuditsReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Films", testFilmsSelect)
	t.Run("FilmsAudits", testFilmsAuditsSelect)
	t.Run("Serieses", testSeriesesSelect)
	t.Run("SeriesesAudits", testSeriesesAuditsSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Films", testFilmsUpdate)
	t.Run("FilmsAudits", testFilmsAuditsUpdate)
	t.Run("Serieses", testSeriesesUpdate)
	t.Run("SeriesesAudits", testSeriesesAuditsUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Films", testFilmsSliceUpdateAll)
	t.Run("FilmsAudits", testFilmsAuditsSliceUpdateAll)
	t.Run("Serieses", testSeriesesSliceUpdateAll)
	t.Run("SeriesesAudits", testSeriesesAuditsSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
