// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Films         string
	FilmsAudit    string
	Serieses      string
	SeriesesAudit string
	Users         string
}{
	Films:         "films",
	FilmsAudit:    "films_audit",
	Serieses:      "serieses",
	SeriesesAudit: "serieses_audit",
	Users:         "users",
}
