// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testFilms(t *testing.T) {
	t.Parallel()

	query := Films()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testFilmsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Films().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFilmsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Films().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Films().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFilmsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FilmSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Films().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFilmsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := FilmExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Film exists: %s", err)
	}
	if !e {
		t.Errorf("Expected FilmExists to return true, but got false.")
	}
}

func testFilmsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	filmFound, err := FindFilm(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if filmFound == nil {
		t.Error("want a record, got nil")
	}
}

func testFilmsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Films().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testFilmsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Films().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testFilmsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	filmOne := &Film{}
	filmTwo := &Film{}
	if err = randomize.Struct(seed, filmOne, filmDBTypes, false, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}
	if err = randomize.Struct(seed, filmTwo, filmDBTypes, false, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = filmOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = filmTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Films().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testFilmsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	filmOne := &Film{}
	filmTwo := &Film{}
	if err = randomize.Struct(seed, filmOne, filmDBTypes, false, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}
	if err = randomize.Struct(seed, filmTwo, filmDBTypes, false, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = filmOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = filmTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Films().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func filmBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Film) error {
	*o = Film{}
	return nil
}

func filmAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Film) error {
	*o = Film{}
	return nil
}

func filmAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Film) error {
	*o = Film{}
	return nil
}

func filmBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Film) error {
	*o = Film{}
	return nil
}

func filmAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Film) error {
	*o = Film{}
	return nil
}

func filmBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Film) error {
	*o = Film{}
	return nil
}

func filmAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Film) error {
	*o = Film{}
	return nil
}

func filmBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Film) error {
	*o = Film{}
	return nil
}

func filmAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Film) error {
	*o = Film{}
	return nil
}

func testFilmsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Film{}
	o := &Film{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, filmDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Film object: %s", err)
	}

	AddFilmHook(boil.BeforeInsertHook, filmBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	filmBeforeInsertHooks = []FilmHook{}

	AddFilmHook(boil.AfterInsertHook, filmAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	filmAfterInsertHooks = []FilmHook{}

	AddFilmHook(boil.AfterSelectHook, filmAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	filmAfterSelectHooks = []FilmHook{}

	AddFilmHook(boil.BeforeUpdateHook, filmBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	filmBeforeUpdateHooks = []FilmHook{}

	AddFilmHook(boil.AfterUpdateHook, filmAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	filmAfterUpdateHooks = []FilmHook{}

	AddFilmHook(boil.BeforeDeleteHook, filmBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	filmBeforeDeleteHooks = []FilmHook{}

	AddFilmHook(boil.AfterDeleteHook, filmAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	filmAfterDeleteHooks = []FilmHook{}

	AddFilmHook(boil.BeforeUpsertHook, filmBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	filmBeforeUpsertHooks = []FilmHook{}

	AddFilmHook(boil.AfterUpsertHook, filmAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	filmAfterUpsertHooks = []FilmHook{}
}

func testFilmsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Films().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFilmsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(filmColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Films().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFilmToOneUserUsingContributingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Film
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, filmDBTypes, false, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.ContributedBy = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.ContributingUser().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := FilmSlice{&local}
	if err = local.L.LoadContributingUser(ctx, tx, false, (*[]*Film)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.ContributingUser == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.ContributingUser = nil
	if err = local.L.LoadContributingUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.ContributingUser == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testFilmToOneSeriesUsingSeries(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Film
	var foreign Series

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, seriesDBTypes, false, seriesColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Series struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.SeriesID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Series().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := FilmSlice{&local}
	if err = local.L.LoadSeries(ctx, tx, false, (*[]*Film)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Series == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Series = nil
	if err = local.L.LoadSeries(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Series == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testFilmToOneSetOpUserUsingContributingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Film
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, filmDBTypes, false, strmangle.SetComplement(filmPrimaryKeyColumns, filmColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetContributingUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.ContributingUser != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.ContributedFilms[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.ContributedBy != x.ID {
			t.Error("foreign key was wrong value", a.ContributedBy)
		}

		zero := reflect.Zero(reflect.TypeOf(a.ContributedBy))
		reflect.Indirect(reflect.ValueOf(&a.ContributedBy)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.ContributedBy != x.ID {
			t.Error("foreign key was wrong value", a.ContributedBy, x.ID)
		}
	}
}
func testFilmToOneSetOpSeriesUsingSeries(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Film
	var b, c Series

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, filmDBTypes, false, strmangle.SetComplement(filmPrimaryKeyColumns, filmColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, seriesDBTypes, false, strmangle.SetComplement(seriesPrimaryKeyColumns, seriesColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, seriesDBTypes, false, strmangle.SetComplement(seriesPrimaryKeyColumns, seriesColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Series{&b, &c} {
		err = a.SetSeries(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Series != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.SeriesFilms[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.SeriesID, x.ID) {
			t.Error("foreign key was wrong value", a.SeriesID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.SeriesID))
		reflect.Indirect(reflect.ValueOf(&a.SeriesID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.SeriesID, x.ID) {
			t.Error("foreign key was wrong value", a.SeriesID, x.ID)
		}
	}
}

func testFilmToOneRemoveOpSeriesUsingSeries(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Film
	var b Series

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, filmDBTypes, false, strmangle.SetComplement(filmPrimaryKeyColumns, filmColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, seriesDBTypes, false, strmangle.SetComplement(seriesPrimaryKeyColumns, seriesColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetSeries(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveSeries(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Series().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Series != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.SeriesID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.SeriesFilms) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testFilmsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testFilmsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FilmSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testFilmsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Films().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	filmDBTypes = map[string]string{`ID`: `integer`, `Title`: `character varying`, `Descriptions`: `character varying`, `DateReleased`: `date`, `Duration`: `integer`, `SeriesID`: `integer`, `SeasonNumber`: `integer`, `EpisodeNumber`: `integer`, `ContributedBy`: `integer`, `ContributedAt`: `timestamp with time zone`, `Invalidation`: `character varying`}
	_           = bytes.MinRead
)

func testFilmsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(filmPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(filmAllColumns) == len(filmPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Films().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, filmDBTypes, true, filmPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testFilmsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(filmAllColumns) == len(filmPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Film{}
	if err = randomize.Struct(seed, o, filmDBTypes, true, filmColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Films().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, filmDBTypes, true, filmPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(filmAllColumns, filmPrimaryKeyColumns) {
		fields = filmAllColumns
	} else {
		fields = strmangle.SetComplement(
			filmAllColumns,
			filmPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := FilmSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testFilmsUpsert(t *testing.T) {
	t.Parallel()

	if len(filmAllColumns) == len(filmPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Film{}
	if err = randomize.Struct(seed, &o, filmDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Film: %s", err)
	}

	count, err := Films().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, filmDBTypes, false, filmPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Film struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Film: %s", err)
	}

	count, err = Films().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
