# This workflow will test a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Lint

on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest